-- ============================================================
BEGIN;
-- STATE AGENCIES
INSERT INTO state_agencies (name, type, status) VALUES
  ('AERONAUTICS COMMISSION', 'state_agency', 'active'),
  ('AIKEN TECHNICAL COLLEGE', 'technical_college', 'active'),
  ('ALLENDALE COUNTY', 'other', 'active'),
  ('CENTRAL CAROLINA TECHNICAL COLLEGE', 'technical_college', 'active'),
  ('CLEMSON UNIVERSITY', 'university', 'active'),
  ('COASTAL CAROLINA UNIVERSITY', 'university', 'active'),
  ('COMMISSION FOR THE BLIND', 'state_agency', 'active'),
  ('College of Charleston', 'university', 'active'),
  ('DARLINGTON COUNTY', 'other', 'active'),
  ('DENMARK TECHNICAL COLLEGE', 'technical_college', 'active'),
  ('DEPARTMENT OF ADMINISTRATION', 'state_agency', 'active'),
  ('DEPARTMENT OF AGRICULTURE', 'state_agency', 'active'),
  ('DEPARTMENT OF BEHAVIORAL HEALTH AND DEVELOPMENTAL DISABILITIES', 'state_agency', 'active'),
  ('DEPARTMENT OF COMMERCE', 'state_agency', 'active'),
  ('DEPARTMENT OF CORRECTIONS', 'state_agency', 'active'),
  ('DEPARTMENT OF EDUCATION', 'state_agency', 'active'),
  ('DEPARTMENT OF EMPLOYMENT AND WORKFORCE', 'state_agency', 'active'),
  ('DEPARTMENT OF ENVIRONMENTAL SERVICES', 'state_agency', 'active'),
  ('DEPARTMENT OF JUVENILE JUSTICE', 'state_agency', 'active'),
  ('DEPARTMENT OF LABOR, LICENSING AND REGULATIONS', 'state_agency', 'active'),
  ('DEPARTMENT OF MOTOR VEHICLES', 'state_agency', 'active'),
  ('DEPARTMENT OF NATURAL RESOURCES', 'state_agency', 'active'),
  ('DEPARTMENT OF PARKS, RECREATION AND TOURISM', 'state_agency', 'active'),
  ('DEPARTMENT OF PUBLIC HEALTH', 'state_agency', 'active'),
  ('DEPARTMENT OF PUBLIC SAFETY', 'state_agency', 'active'),
  ('DEPARTMENT OF TRANSPORTATION', 'state_agency', 'active'),
  ('DEPARTMENT OF VETERANS AFFAIRS', 'state_agency', 'active'),
  ('EDUCATIONAL TELEVISION COMMISSION', 'broadcast', 'active'),
  ('EMERGENCY MANAGEMENT DIVISION', 'state_agency', 'active'),
  ('FLORENCE-DARLINGTON TECHNICAL COLLEGE', 'technical_college', 'active'),
  ('FORESTRY COMMISSION', 'state_agency', 'active'),
  ('FRANCIS MARION UNIVERSITY', 'university', 'active'),
  ('GREENVILLE TECHNICAL COLLEGE', 'technical_college', 'active'),
  ('H73 VOCATIONAL REHABILITATION DEPARTMENT', 'other', 'active'),
  ('HORRY-GEORGETOWN TECHNICAL COLLEGE', 'technical_college', 'active'),
  ('LANDER UNIVERSITY', 'university', 'active'),
  ('LAW ENFORCEMENT TRAINING COUNCIL (CRIMINAL JUSTICE ACADEMY)', 'other', 'active'),
  ('MEDICAL UNIVERSITY OF SOUTH CAROLINA', 'medical', 'active'),
  ('MIDLANDS TECHNICAL COLLEGE', 'technical_college', 'active'),
  ('NORTHEASTERN TECHNICAL COLLEGE', 'technical_college', 'active'),
  ('OFFICE OF THE ADJUTANT GENERAL', 'military', 'active'),
  ('ORANGEBURG-CALHOUN TECHNICAL COLLEGE', 'technical_college', 'active'),
  ('PIEDMONT TECHNICAL COLLEGE', 'technical_college', 'active'),
  ('PUBLIC EMPLOYEE BENEFITS AUTHORITY', 'state_agency', 'active'),
  ('Patriots Point Development Authority', 'other', 'active'),
  ('SC GOVERNOR''S SCHOOL OF AGRICULTURE AT JOHN LA HOWE', 'other', 'active'),
  ('SC Governor''s School for Science and Mathematics', 'other', 'active'),
  ('SC Governor''s School for the Arts & Humanities', 'other', 'active'),
  ('SCHOOL FOR THE DEAF & BLIND', 'other', 'active'),
  ('SOUTH CAROLINA STATE UNIVERSITY', 'university', 'active'),
  ('SPARTANBURG COMMUNITY COLLEGE', 'technical_college', 'active'),
  ('STATE LAW ENFORCEMENT DIVISION', 'law_enforcement', 'active'),
  ('TECHNICAL COLLEGE OF THE LOWCOUNTRY', 'technical_college', 'active'),
  ('TRIDENT TECHNICAL COLLEGE', 'technical_college', 'active'),
  ('The Citadel', 'university', 'active'),
  ('UNIVERSITY OF SOUTH CAROLINA - AIKEN CAMPUS', 'university', 'active'),
  ('UNIVERSITY OF SOUTH CAROLINA - BEAUFORT CAMPUS', 'university', 'active'),
  ('UNIVERSITY OF SOUTH CAROLINA - COLUMBIA CAMPUS', 'university', 'active'),
  ('UNIVERSITY OF SOUTH CAROLINA - HILTON HEAD CAMPUS', 'other', 'active'),
  ('UNIVERSITY OF SOUTH CAROLINA - SALKEHATCHIE CAMPUS', 'university', 'active'),
  ('UNIVERSITY OF SOUTH CAROLINA - SUMTER CAMPUS', 'university', 'active'),
  ('UNIVERSITY OF SOUTH CAROLINA - UNION CAMPUS', 'university', 'active'),
  ('UNIVERSITY OF SOUTH CAROLINA - UPSTATE CAMPUS', 'university', 'active'),
  ('UNIVERSITY OF SOUTH CAROLINA LANCASTER', 'university', 'active'),
  ('VOCATIONAL REHABILITATION DEPARTMENT', 'other', 'active'),
  ('WIL LOU GRAY OPPORTUNITY SCHOOL', 'other', 'active'),
  ('WINTHROP UNIVERSITY', 'university', 'active'),
  ('YORK TECHNICAL COLLEGE', 'technical_college', 'active');

-- LICENSEES
INSERT INTO licensees (name, licensee_type, status) VALUES
  ('AT&T: New Cingular Wireless PCS, LLC', 'carrier', 'active'),
  ('AT&T: New Cingular Wireless PCS, LLC (Temporary)', 'carrier', 'active'),
  ('Cherokee County', 'government', 'active'),
  ('FBI', 'government', 'active'),
  ('Farmer''s Telephone Cooperative (FTC)', 'carrier', 'active'),
  ('Gray Media Group Inc. dba WMBF', 'broadcast', 'active'),
  ('Horry Telephone Cooperative, Inc.', 'carrier', 'active'),
  ('K-Love Educational Media Foundation', 'broadcast', 'active'),
  ('NOAA/AGO/EAD', 'government', 'active'),
  ('NOAA/AGO/EAD- SBT PO', 'government', 'active'),
  ('SANTEE COOPER: SC Public Svc Authority', 'government', 'active'),
  ('SC DNR: Dept of Natural Resources', 'government', 'active'),
  ('SC DOA/DTO: Dept of Admin, Div. of Technology Ops', 'government', 'active'),
  ('SLED', 'government', 'active'),
  ('Sinclair Communications LLC, d/b/a WLOS/WMYA-TV', 'broadcast', 'active'),
  ('T-MOBILE', 'carrier', 'active'),
  ('T-Mobile (Formerly: SPRINT: Airgate PCS, Inc, a Delaware Corporation)', 'carrier', 'active'),
  ('U.S. Customs and Border Protection', 'government', 'active'),
  ('U.S. Federal Aviation Administration (FAA)', 'government', 'active'),
  ('VERIZON: AllTel Communications, Inc.', 'carrier', 'active'),
  ('VERIZON: AllTel Corporation', 'carrier', 'active'),
  ('VERIZON: Cellco Partnership', 'carrier', 'active'),
  ('VERIZON: Charleston-N Chas MSA Limited Partnership', 'carrier', 'active'),
  ('WCCP-FM', 'broadcast', 'active');

COMMIT;